# Generated by Django 4.0.4 on 2022-05-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AirManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='channels',
            field=models.CharField(default=0, max_length=21),
            preserve_default=False,
        ),
    ]
